name: lab_4

services:
  lab4:
    build:
      context: .
      dockerfile: Dockerfile
      target: lab4
    image: lab_4:lab4
    volumes:
      - .:/work
    command: ["bash", "/work/scripts/demo.sh"]

  winetest:
    build:
      context: .
      dockerfile: Dockerfile
      target: winetest
    image: lab_4:winetest
    volumes:
      - .:/work
    command: ["bash", "/work/scripts/wine_run.sh"]
